In [1]:
import numpy as np
import pandas as pd
import json

In [2]:
train_data = pd.read_csv('/Users/rimmavahreeva/Desktop/detection_pet_project/SKU110K/train/annotations_train.csv')

In [3]:
train_data.head()

    image_name    x1    y1    x2    y2   class  image_width  image_height
0  train_0.jpg   208   537   422   814  object         3024          3024
1  train_0.jpg  1268  1923  1365  2209  object         3024          3024
2  train_0.jpg  1135  2074  1261  2166  object         3024          3024
3  train_0.jpg  1045  2085  1122  2258  object         3024          3024
4  train_0.jpg   976  2036  1040  2177  object         3024          3024

In [4]:
temp_train_data = train_data[['image_name', 'image_width', 'image_height']].drop_duplicates(subset=['image_name'])
train_images = []
filenames_to_idx = {}
for idx, (_, (filename, w, h)) in enumerate(temp_train_data.iterrows()):
    filenames_to_idx[filename] = idx
    train_images.append({
        'idx': idx,
        'width': w,
        'height': h,
        'file_name': filename
    })

In [5]:
temp_train_data.head()

         image_name  image_width  image_height
0       train_0.jpg         3024          3024
141     train_1.jpg         1920          2560
276    train_10.jpg         2448          3264
432   train_100.jpg         2448          3264
597  train_1000.jpg         2448          3264

In [6]:
train_annotations_id = []
for idx in enumerate(train_data['image_name']):
    train_annotations_id.append(idx)
dict_train_annotations_id = dict(train_annotations_id)

In [7]:
train_categories = [{"id": 0, "name": 'item'}]

In [8]:
train_annotations = []
for idx, (_, row) in enumerate(train_data.iterrows()):
    current_filename = row['image_name']
    image_index = filenames_to_idx[current_filename]
    x1, y1, x2, y2 = row[['x1', 'y1', 'x2', 'y2']]
    width = x2 - x1
    height = y2 - y1
    
    train_annotations.append({
        'id': idx,
        'image_id': image_index,
        'category_id': 0,
        "area": width * height,
        "bbox": [x1, y1, width, height],
        "iscrowd": 0
    })

In [9]:
train_coco_ans = {"images": train_images, "annotations": train_annotations, 'categories': train_categories}

In [10]:
with open('./train.json', 'w') as f:
    json.dump(train_coco_ans, f)

In [11]:
test_data = pd.read_csv('/Users/rimmavahreeva/Desktop/detection_pet_project/SKU110K/test/annotations_test.csv')

In [12]:
test_data.head()

   image_name   x1    y1   x2    y2   class  image_width  image_height
0  test_0.jpg  120  2527  225  2764  object         2448          3264
1  test_0.jpg  727  2269  862  2376  object         2448          3264
2  test_0.jpg  463  2274  715  2434  object         2448          3264
3  test_0.jpg  158  2290  283  2444  object         2448          3264
4  test_0.jpg    0  2290  154  2456  object         2448          3264

In [13]:
temp_test_data = test_data[['image_name', 'image_width', 'image_height']].drop_duplicates(subset=['image_name'])
test_images = []
filenames_to_idx = {}
for idx, (_, (filename, w, h)) in enumerate(temp_test_data.iterrows()):
    filenames_to_idx[filename] = idx
    test_images.append({
        'idx': idx,
        'width': w,
        'height': h,
        'file_name': filename
    })

In [14]:
temp_test_data.head()

        image_name  image_width  image_height
0       test_0.jpg         2448          3264
121     test_1.jpg         1920          2560
253    test_10.jpg         2340          4160
396   test_100.jpg         1920          2560
550  test_1000.jpg         2448          3264

In [15]:
test_annotations_id = []
for idx in enumerate(temp_test_data['image_name']):
    test_annotations_id.append(idx)
dict_test_annotations_id = dict(test_annotations_id)

In [16]:
test_categories = [{"id": 0, "name": 'item'}]

In [17]:
test_annotations = []
for idx, (_, row) in enumerate(test_data.iterrows()):
    current_filename = row['image_name']
    image_index = filenames_to_idx[current_filename]
    x1, y1, x2, y2 = row[['x1', 'y1', 'x2', 'y2']]
    width = x2 - x1
    height = y2 - y1
    
    test_annotations.append({
        'id': idx,
        'image_id': image_index,
        'category_id': 0,
        "area": width * height,
        "bbox": [x1, y1, width, height],
        "iscrowd": 0
    })

In [18]:
test_coco_ans = {"images": test_images, "annotations": test_annotations, 'categories': test_categories}

In [19]:
with open('./test.json', 'w') as f:
    json.dump(test_coco_ans, f)

In [20]:
val_data = pd.read_csv('/Users/rimmavahreeva/Desktop/detection_pet_project/SKU110K/val/annotations_val.csv')

In [21]:
val_data.head()

  image_name   x1    y1    x2    y2   class  image_width  image_height
0  val_0.jpg    5  1429   219  1612  object         2336          4160
1  val_0.jpg  467  1066   589  1330  object         2336          4160
2  val_0.jpg  602  1085   739  1329  object         2336          4160
3  val_0.jpg  756  1090   894  1368  object         2336          4160
4  val_0.jpg  899  1095  1042  1376  object         2336          4160

In [22]:
temp_val_data = val_data[['image_name', 'image_width', 'image_height']].drop_duplicates(subset=['image_name'])
val_images = []
filenames_to_idx = {}
for idx, (_, (filename, w, h)) in enumerate(temp_val_data.iterrows()):
    filenames_to_idx[filename] = idx
    val_images.append({
        'idx': idx,
        'width': w,
        'height': h,
        'file_name': filename
    })

In [23]:
temp_val_data.head()

      image_name  image_width  image_height
0      val_0.jpg         2336          4160
157    val_1.jpg         2448          3264
323   val_10.jpg         2340          4160
458  val_100.jpg         2448          3264
597  val_101.jpg         2448          3264

In [25]:
val_annotations_id = []
for idx in enumerate(val_data['image_name']):
    val_annotations_id.append(idx)
dict_val_annotations_id = dict(val_annotations_id)

In [26]:
val_categories = [{"id": 0, "name": 'item'}]

In [27]:
val_annotations = []
for idx, (_, row) in enumerate(val_data.iterrows()):
    current_filename = row['image_name']
    image_index = filenames_to_idx[current_filename]
    x1, y1, x2, y2 = row[['x1', 'y1', 'x2', 'y2']]
    width = x2 - x1
    height = y2 - y1
    
    val_annotations.append({
        'id': idx,
        'image_id': image_index,
        'category_id': 0,
        "area": width * height,
        "bbox": [x1, y1, width, height],
        "iscrowd": 0
    })

In [28]:
val_coco_ans = {"images": val_images, "annotations": val_annotations, 'categories': val_categories}

In [29]:
with open('./val.json', 'w') as f:
    json.dump(val_coco_ans, f)